### ISSUE TITLE
[REFACTOR]: 코드 정리하기

### ISSUE THREAD

**Issue by ezcolin2** [TIcket-Timer/backend#19]
## 💡 Issue

1. 현재 소셜 로그인 관련해서 외부 api를 사용 중인데 api 사용 방법이 뒤죽박죽이라 정리가 필요합니다.
2. 메소드 이름 또한 일관성이 없어서 메소드 이름을 일관성있게 변경해야 합니다.
3. 클라이언트로부터 소셜 로그인 토큰을 받아서 유저 정보를 받아오고 있습니다. 그런데 소셜 로그인 토큰을 사용하고나서 만료가 될 때까지 재사용이 가능하다는 단점이 있습니다. 유저 정보를 받아온 후 바로 로그아웃 시키는 과정이 필요해 보입니다.
4. 현재 application.properties 파일의 secret key가 그냥 plain text라서 보안을 위해서 변경이 필요합니다.
5. 현재 닉네임을 UUID로 랜덤 생성하고 앞 부분만 사용 중인데 일부만 사용할 거면 UUID 말고 다른 랜덤 문자 생성을 사용하는게 좋을 것 같습니다.
6. 카카오의 경우 유저 정보를 받아올 때 토큰 앞에 Bearer를 붙이고 애플은 Bearer를 붙이지 않습니다. 그런데 지금은 ios가 인증 서버를 보고 Bearer를 붙일지 말지 결정하는데 이는 부자연스러워 보입니다. 무조건 그냥 토큰을 받고 서버에서 Bearer를 붙일지 말지 판단하도록 바꾸는게 필요합니다.

## 📝  todo
- [x] 외부 api 사용 방법 통일
- [x] 메소드 이름 일관성 있게 변경
- [x] 소셜 로그인 토큰 사용 후 바료 만료
- [x] application.properties 파일의 secret key 변경 
- [x] 닉네임 랜덤 생성 알고리즘 변경
- [x] Bearer 붙일지 말지 결정
